language: java
jdk:
  - oraclejdk9
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
branches:
  only:
    - master
jobs:
  include:
    script: ./gradlew clean build
    deploy:
      provider: releases
      file: pirarucu-jvm/build/distributions/*.zip
      api_key: "$GITHUB_OAUTH_TOKEN"
      skip_cleanup: true
      on:
        tags: true